export const vehiclesFields = [
	{
		category: 'Vehicle Information',
		fields: [
			{
				label: 'Name',
				id: 'name',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Vin',
				id: 'vin_no',
				input: 'input',
				col: '3',
				mandatory: true,
			},
			{
				label: 'Reg No',
				id: 'reg_no',
				input: 'input',
				col: '3',
				mandatory: true,
			},
			{
				label: 'Group',
				id: 'fleetName',
				options: 'fleetName',
				input: 'select',
				placeholder: 'Choose your fleet',
				col: '3',
				mandatory: true,
			},
			{
				label: 'Color',
				id: 'color',
				input: 'input',
				col: '3',
				mandatory: true,
			},
			{
				label: 'Brand',
				id: 'manufacturer',
				options: 'manufacturers',
				input: 'select',
				placeholder: 'Select a brand...',
				col: '3',
				mandatory: true,
				dependentId: 'fleetName',
			},
			{
				label: 'Make',
				id: 'make',
				options: 'makes',
				input: 'select',
				placeholder: 'Select a make...',
				col: '3',
				mandatory: true,
				dependentId: 'manufacturer',
			},
			{
				label: 'Model',
				id: 'model',
				options: 'models',
				input: 'select',
				placeholder: 'Select a model...',
				col: '3',
				mandatory: true,
				dependentId: 'make',
			},
			{
				label: 'Mileage',
				id: 'mileage',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Engine hour',
				id: 'engine_hour',
				input: 'input',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Device/SIM Mapping',
		fields: [
			{
				label: 'Device IMEI',
				id: 'device_imei',
				options: 'imei',
				input: 'select',
				placeholder: 'Select an IMEI...',
				col: '3',
				mandatory: true,
				dependentId: 'fleetName',
			},
			{
				label: 'Mobile number',
				id: 'mobile_no',
				input: 'input',
				dotted: true,
				col: '3',
				mandatory: false,
			},
			{
				label: 'Network type',
				id: 'network_type',
				input: 'input',
				dotted: true,
				col: '3',
				mandatory: false,
			},
			{
				label: 'Carrier',
				id: 'carrier',
				input: 'input',
				dotted: true,
				col: '3',
				mandatory: false,
			},
			{
				label: 'IMSI',
				id: 'imsi',
				input: 'input',
				dotted: true,
				col: '3',
				mandatory: false,
			},
			{
				label: 'Sim number',
				id: 'sim_number',
				dotted: true,
				input: 'input',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Driver Information',
		fields: [
			{
				label: 'Driver full name',
				id: 'driver_name',
				input: 'editable-select',
				options: 'drivers',
				placeholder: 'Select a driver...',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Type and usage',
		fields: [
			{
				label: 'Type',
				id: 'type',
				options: 'types',
				input: 'select',
				placeholder: 'Select a type...',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Fuel type',
				id: 'fuel_type',
				options: 'fuel_type',
				input: 'select',
				placeholder: 'Select a fuel type...',
				col: '3',
				mandatory: true,
			},
			{
				label: 'Fuel average consumption ( L/100Km )',
				id: 'fuel_average_consumption',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Fuel Average consumption during standby (L/hour)',
				id: 'fuel_average_consumption_during_stand_by',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Co2 emission ( G/km )',
				id: 'co2_emission',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Co2 emission during stand by ( G/Hour )',
				id: 'co2_emission_during_stand_by',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Tank capacity',
				id: 'tank_capacity',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Cost per 1L',
				id: 'cost_per_l',
				input: 'input',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Insurance and legal',
		fields: [
			{
				label: 'Insurance policy number',
				id: 'insurance_policy_number',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Insurance expiration time',
				id: 'insurance_expiration_time',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Wheels identification number',
				id: 'wheels_identification_number',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Trailer registration number',
				id: 'trailer_reg_no',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Manufacture year',
				id: 'manufacture_year',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Fiscal HP',
				id: 'fiscal_hp',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Engine type',
				id: 'engine_type',
				options: 'engine_types',
				input: 'select',
				placeholder: 'Select an engine type...',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Purchase date',
				id: 'purchase_date',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Purchase odometer',
				id: 'purchase_odometer',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'End date',
				id: 'end_date',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'End odometer',
				id: 'end_odometer',
				input: 'input',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Dimensions and specifications',
		fields: [
			{
				label: 'Dimensions',
				id: 'dimensionH',
				placeholder: 'H',
				input: 'input',
				col: '1',
				mandatory: false,
			},
			{
				label: '(H x W x L)',
				id: 'dimensionW',
				input: 'input',
				placeholder: 'W',
				col: '1',
				mandatory: false,
			},
			{
				label: '`',
				id: 'dimensionL',
				placeholder: 'L',
				input: 'input',
				col: '1',
				mandatory: false,
			},
			{
				label: 'Permitted speed',
				id: 'permitted_speed',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Trailer registration number',
				id: 'trailer_registration_number',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Tire size',
				id: 'tire_size',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Tire model',
				id: 'tire_model',
				input: 'input',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Fuel card information',
		fields: [
			{
				label: 'Fuel card brand',
				id: 'fuel_card_brand',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Fuel card number',
				id: 'fuel_card_number',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Fuel card ref.',
				id: 'fuel_card_ref',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Fuel card code',
				id: 'fuel_card_code',
				input: 'input',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Service and maintenance',
		fields: [
			{
				label: 'Odometer at last service',
				id: 'odometer_last_service',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Theoretical distance between services (km)',
				id: 'theoretical_distance_between_services',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Theoretical no of days between services',
				id: 'theoretical_number_of_days_between_services',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Contract start date',
				id: 'contract_start_date',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Contract start odometer',
				id: 'contract_start_odometer',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Last technical control date',
				id: 'last_technical_control_date',
				input: 'input',
				col: '3',
				mandatory: false,
			},
			{
				label: 'Car registration date',
				id: 'car_registration_date',
				input: 'input',
				col: '3',
				mandatory: false,
			},
		],
	},
	{
		category: 'Additional information',
		fields: [
			{
				label: 'Additional information',
				id: 'additional_information',
				input: 'textarea',
				col: '12',
				mandatory: false,
			},
		],
	},
];
